# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jFOPNtCNXQGOLTwoblUd0o8C59vVFya
"""

n = int(input("Digite um numero: "))

if n < 0 or n > 9999:
    print("Numero invalido.")
else:
    a = n // 1000
    b = (n % 1000) // 100
    c = (n % 100) // 10
    d = n % 10

    if (a == b == c) or (a == b == d) or (a == c == d) or (b == c == d):
        print("Numero invalido: muitos digitos repetidos.")
    else:
        cont = 0

        while n != 6174:
            a = n // 1000
            b = (n % 1000) // 100
            c = (n % 100) // 10
            d = n % 10

            if a > b:
                a, b = b, a
            if a > c:
                a, c = c, a
            if a > d:
                a, d = d, a
            if b > c:
                b, c = c, b
            if b > d:
                b, d = d, b
            if c > d:
                c, d = d, c

            menor = a * 1000 + b * 100 + c * 10 + d
            maior = d * 1000 + c * 100 + b * 10 + a

            n = maior - menor
            cont = cont + 1

            print("Iteracao", cont, ":", maior, "-", menor, "=", n)

        print("Constante de Kaprekar atingida em", cont, "interações.")